import { defineConfig } from 'oxlint';

export default defineConfig({
	options: {
		typeAware: true,
	},
	ignorePatterns: ['dist/**', 'tmp/**', '.agents/**', '.claude/**', '.codex/**', '.cursor/**'],
	categories: {
		correctness: 'error',
		suspicious: 'error',
		perf: 'off',
		style: 'off',
		restriction: 'off',
		pedantic: 'off',
		nursery: 'off',
	},
	plugins: ['typescript', 'unicorn', 'import', 'promise', 'oxc'],
	jsPlugins: [
		'@victor-software-house/anti-slop',
		{
			name: '@limegrass/import-alias',
			specifier: '@limegrass/eslint-plugin-import-alias',
		},
	],
	rules: {
		'no-console': 'error',
		complexity: ['error', { max: 20, variant: 'modified' }],
		'import/no-default-export': 'error',
		'import/no-cycle': 'error',
		'import/extensions': [
			'error',
			'never',
			{
				ignorePackages: true,
				pattern: {
					liquid: 'always',
					md: 'always',
					example: 'always',
					json: 'always',
					sh: 'always',
				},
			},
		],
		'typescript/no-explicit-any': 'error',
		'typescript/no-non-null-assertion': 'error',
		'typescript/consistent-type-imports': 'error',
		'typescript/no-unused-vars': 'error',
		'typescript/no-floating-promises': 'error',
		'typescript/no-misused-promises': 'error',
		'typescript/await-thenable': 'error',
		'typescript/strict-boolean-expressions': 'error',
		'typescript/no-unnecessary-type-assertion': 'error',
		'typescript/no-unsafe-type-assertion': 'error',
		'typescript/no-unsafe-assignment': 'error',
		'typescript/no-unsafe-call': 'error',
		'typescript/no-unsafe-member-access': 'error',
		'typescript/no-unsafe-return': 'error',
		'typescript/no-unsafe-argument': 'error',
		'typescript/no-deprecated': 'error',
		'typescript/consistent-type-assertions': 'error',
		'unicorn/prefer-node-protocol': 'error',
		'unicorn/no-array-for-each': 'error',
		'unicorn/no-null': 'off',
		'promise/always-return': 'error',
		'promise/no-return-wrap': 'error',
		'anti-slop/no-chained-type-assertions': 'error',
		'anti-slop/no-conditional-empty-object-spread': 'error',
		'anti-slop/no-known-value-widening': 'error',
		'anti-slop/no-module-mocking': 'error',
		'anti-slop/no-object-parameters': 'error',
		'anti-slop/no-reflect-apply': 'error',
		'anti-slop/no-reflect-get': 'error',
		'anti-slop/no-runtime-typeof': ['error', { allowInTypeGuards: true }],
		'anti-slop/no-shape-in-symbol-names': 'error',
		'anti-slop/no-unknown-parameters': 'error',
		'anti-slop/no-unknown-returns': 'error',
		'anti-slop/no-unknown-type-aliases': 'error',
		'anti-slop/no-unsafe-dictionary-type': 'error',
		'anti-slop/no-widen-then-assert': 'error',
		'anti-slop/require-safety-comment-for-type-assertion': 'error',
		'@limegrass/import-alias/import-alias': 'error',
	},
	overrides: [
		{
			files: [
				'oxlint.config.ts',
				'tsdown.config.ts',
				'commitlint.config.ts',
				'src/index.ts',
				'.changeset/changelog.ts',
			],
			rules: {
				'import/no-default-export': 'off',
			},
		},
		{
			files: ['test/**', 'mise-tasks/**'],
			rules: {
				'@limegrass/import-alias/import-alias': 'off',
			},
		},
	],
});
