import { defineConfig } from 'oxlint';

export default defineConfig({
	options: {
		typeAware: true,
	},
	ignorePatterns: ['dist/**', 'tmp/**', '.agents/**', '.claude/**', '.codex/**', '.cursor/**'],
	categories: {
		correctness: 'error',
		suspicious: 'error',
		perf: 'off',
		style: 'off',
		restriction: 'off',
		pedantic: 'off',
		nursery: 'off',
	},
	plugins: ['typescript', 'unicorn', 'import', 'promise', 'oxc'],
	jsPlugins: [
		'@victor-software-house/anti-slop',
		{
			name: 'zod',
			specifier: 'eslint-plugin-zod',
		},
		{
			name: '@limegrass/import-alias',
			specifier: '@limegrass/eslint-plugin-import-alias',
		},
	],
	rules: {
		'no-console': 'error',
		complexity: ['error', { max: 20, variant: 'modified' }],
		'import/no-default-export': 'error',
		'import/no-cycle': 'error',
		'import/extensions': [
			'error',
			'never',
			{
				ignorePackages: true,
				pattern: {
					liquid: 'always',
					md: 'always',
					example: 'always',
					json: 'always',
					sh: 'always',
				},
			},
		],
		'typescript/no-explicit-any': 'error',
		'typescript/no-non-null-assertion': 'error',
		'typescript/consistent-type-imports': 'error',
		'typescript/no-unused-vars': 'error',
		'typescript/no-floating-promises': 'error',
		'typescript/no-misused-promises': 'error',
		'typescript/await-thenable': 'error',
		'typescript/strict-boolean-expressions': 'error',
		'typescript/no-unnecessary-type-assertion': 'error',
		'typescript/no-unsafe-type-assertion': 'error',
		'typescript/no-unsafe-assignment': 'error',
		'typescript/no-unsafe-call': 'error',
		'typescript/no-unsafe-member-access': 'error',
		'typescript/no-unsafe-return': 'error',
		'typescript/no-unsafe-argument': 'error',
		'typescript/no-deprecated': 'error',
		'typescript/consistent-type-assertions': 'error',
		'unicorn/prefer-node-protocol': 'error',
		'unicorn/no-array-for-each': 'error',
		'unicorn/no-null': 'off',
		'promise/always-return': 'error',
		'promise/no-return-wrap': 'error',
		'anti-slop/no-chained-type-assertions': 'error',
		'anti-slop/no-conditional-empty-object-spread': 'error',
		'anti-slop/no-known-value-widening': 'error',
		'anti-slop/no-module-mocking': 'error',
		'anti-slop/no-object-parameters': 'error',
		'anti-slop/no-reflect-apply': 'error',
		'anti-slop/no-reflect-get': 'error',
		'anti-slop/no-runtime-typeof': ['error', { allowInTypeGuards: true }],
		'anti-slop/no-shape-in-symbol-names': 'error',
		'anti-slop/no-unknown-parameters': 'error',
		'anti-slop/no-unknown-returns': 'error',
		'anti-slop/no-unknown-type-aliases': 'error',
		'anti-slop/no-unsafe-dictionary-type': 'error',
		'anti-slop/no-widen-then-assert': 'error',
		'anti-slop/require-safety-comment-for-type-assertion': 'error',
		'zod/array-style': 'error',
		'zod/consistent-import': 'error',
		'zod/consistent-import-source': [
			'error',
			{
				sources: ['zod', 'zod/v4'],
			},
		],
		'zod/consistent-schema-var-name': 'error',
		'zod/no-any-schema': 'error',
		'zod/no-coerce-boolean': 'error',
		'zod/no-duplicate-schema-methods': 'error',
		'zod/no-empty-custom-schema': 'error',
		'zod/no-native-enum': 'error',
		'zod/no-number-schema-with-finite': 'error',
		'zod/no-number-schema-with-int': 'error',
		'zod/no-number-schema-with-is-finite': 'error',
		'zod/no-number-schema-with-is-int': 'error',
		'zod/no-number-schema-with-safe': 'error',
		'zod/no-number-schema-with-step': 'error',
		'zod/no-optional-and-default-together': [
			'error',
			{
				preferredMethod: 'default',
			},
		],
		'zod/no-promise-schema': 'error',
		'zod/no-schema-with-is-nullable': 'error',
		'zod/no-schema-with-is-optional': 'error',
		'zod/no-throw-in-refine': 'error',
		'zod/no-transform-in-record-key': 'error',
		'zod/no-unknown-schema': 'off',
		'zod/prefer-enum-over-literal-union': 'error',
		'zod/prefer-meta': 'error',
		'zod/prefer-meta-last': 'error',
		'zod/prefer-strict-object': 'error',
		'zod/prefer-string-schema-with-trim': 'error',
		'zod/prefer-top-level-string-formats': 'error',
		'zod/prefer-trim-before-string-length-checks': 'error',
		'zod/require-brand-type-parameter': 'error',
		'zod/require-error-message': 'error',
		'zod/schema-error-property-style': 'error',
		'@limegrass/import-alias/import-alias': [
			'error',
			{
				aliasConfigPath: 'tsconfig.json',
			},
		],
	},
	overrides: [
		{
			files: [
				'openapi-ts.config.ts',
				'src/index.ts',
				'.changeset/changelog.ts',
				'commitlint.config.ts',
				'tsdown.config.ts',
				'oxlint.config.ts',
			],
			rules: {
				'import/no-default-export': 'off',
			},
		},
		{
			files: [
				'src/generated/client/**',
				'src/generated/core/**',
				'src/generated/sdk.gen.ts',
				'src/generated/client.gen.ts',
				'src/generated/types.gen.ts',
			],
			rules: {
				complexity: 'off',
				'no-shadow': 'off',
				'no-underscore-dangle': 'off',
				'typescript/no-explicit-any': 'off',
				'typescript/no-non-null-assertion': 'off',
				'typescript/no-misused-spread': 'off',
				'typescript/no-unsafe-assignment': 'off',
				'typescript/no-unsafe-return': 'off',
				'typescript/no-unsafe-argument': 'off',
				'typescript/no-unsafe-type-assertion': 'off',
				'typescript/strict-boolean-expressions': 'off',
				'typescript/consistent-return': 'off',
				'typescript/no-redundant-type-constituents': 'off',
				'typescript/no-unnecessary-type-parameters': 'off',
				'typescript/no-floating-promises': 'off',
				'unicorn/no-array-for-each': 'off',
				'unicorn/no-array-sort': 'off',
				'unicorn/consistent-function-scoping': 'off',
				'anti-slop/no-shape-in-symbol-names': 'off',
				'anti-slop/no-runtime-typeof': 'off',
				'anti-slop/require-safety-comment-for-type-assertion': 'off',
				'anti-slop/no-unsafe-dictionary-type': 'off',
				'anti-slop/no-unknown-parameters': 'off',
				'anti-slop/no-unknown-returns': 'off',
				'anti-slop/no-known-value-widening': 'off',
				'anti-slop/no-conditional-empty-object-spread': 'off',
			},
		},
	],
});
